baseURL                          = "https://dimisik.github.io"  # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "dsike (at) unm (dot) edu"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "small"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = true                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "America/Denver"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = false
        facebook                 = false
        googlePlus               = false
        pinterest                = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://linkedin.com/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"    
    [[params.social]]
        url   = "https://www.researchgate.net/profile/Dimitrios_Sikeridis"
        icon  = "researchgate" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://scholar.google.com/citations?user=b-cYmRsAAAAJ&hl=en&oi=sra"
        icon  = "google" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://github.com/dimisik"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = "rel=\"me\"" # Add rel attribute for Mastodon profile link verification
    [[params.social]]
        url = "mailto:dsike@unm.edu"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"

# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Dimitris Sikeridis"
        [languages.en.params]
            description  = "Personal Webpage"   # Max 160 characters show in search results
            footerText   = "© 2020 Dimitris Sikeridis · [Apache-2.0](https://github.com/victoriadrake/hugo-theme-introduction/blob/master/LICENSE) · Powered by the [Introduction theme](https://github.com/victoriadrake/hugo-theme-introduction) for [Hugo](https://gohugo.io)"                      # Text to override default footer text (markdown allowed)

    # [languages.es]
    #     languageName     = "Español"
    #     languageCode     = "es"
    #     contentDir       = "content/es"
    #     weight           = 1
    #     title            = "Introducción"
    #     [languages.es.params]
    #         description  = "Descripcion del sitio web"
    #         # footerText   = ""

    # [languages.de]
    #     languageName     = "Deutsch"
    #     languageCode     = "de"
    #     contentDir       = "content/de"
    #     weight           = 2
    #     title            = "Vorstellung"
    #     [languages.de.params]
    #         dateFormat   = "2. January 2006"
    #         description  = "Beschreibung der Webseite"
    #         # footerText   = ""
